# -*- coding: utf-8 -*-
"""pdftoimage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nCKmP0Ay6wrZTiyyXklb0c1fdxVCWtBj
"""

headings = [('DETAILED OPERATIONAL PLAN', 'THE BUDGET'), ('Achievement Against Outcomes', 'Contact Information'), ('Achievement Against Outcomes', 'Contact Information'), ('Progress towards objectives', 'Contact Information'), ('Analysis of the operation','Lessons learned')]

!pip install PyMuPDF

import fitz
!pip install PyPDF2
from PyPDF2 import PdfReader

# creating a pdf file object
pdfFileObj = open('/content/MDRKZ007dfr.pdf', 'rb')

# creating a pdf reader object
pdfReader = PdfReader(pdfFileObj)

startPage = 0
endPage = 0
for i in range(0, len(pdfReader.pages)):
  pageObj = pdfReader.pages[i]
  content = pageObj.extract_text()
  text = str(content).replace("  ", " ")
  if 'detailed operational plan' in text.lower():
    startPage = i
    j = i + 1
    while j < len(pdfReader.pages):
      pageObj2 = pdfReader.pages[j]
      content2 = pageObj2.extract_text()
      text2 = str(content2).replace("  ", " ")
      if 'the budget' in text2.lower():
        endPage = j
        break
      j += 1


print(startPage, endPage)

pdffile = "/content/MDRCL011dfr.pdf"
doc = fitz.open(pdffile)
zoom = 4
mat = fitz.Matrix(zoom, zoom)

for k in range(startPage, endPage + 1):
  print(k)
  val = f"image_{k + 1}.png"
  page = doc.load_page(k)
  pix = page.get_pixmap(matrix=mat)
  pix.save(val)
doc.close()